### PR TITLE
Updated to latest version of the neatline plugin

### PR DESCRIPTION
**Pull request by jamiefolsom**
Also added an alternative command to the docker image readme

### CODE REVIEW

**Comment by jamiefolsom** [comment]
@jeremyboggs and @ZoeLeBlanc any thoughts on that additional command? Without it, the submodule update step didn't actually pull the most recent version of the submodule code for me. 

Otherwise the only change here should be the resulting update of the neatline submodule to latest master, which I think we'll want to do periodically. Thanks!

**Comment by ZoeLeBlanc** [comment]
@jamiefolsom this looks good to me 👍 ! I was just going into each folder and pulling master manually so thanks for the time save!

**Comment by jamiefolsom** [comment]
@ZoeLeBlanc or @jeremyboggs when you have a chance, would you merge to master, or provide me with write access to the repo, and I'd be glad to do it. Thanks!

**Comment by jamiefolsom** [comment]
Thx, @jeremyboggs! I'll be updating it again early next week, with the latest code.

**Pull request merged**
